name: flutter_project_august
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # State Management
  mobx: ^2.1.3+1
  flutter_mobx: ^2.0.6+5
  provider:
  mobx_codegen:

  # Localization
  easy_localization:

  # Cache
  shared_preferences: ^2.0.17

  # Network
  dio:

  # Serializable
  json_serializable:
  cupertino_icons: ^1.0.2
  sqflite: ^2.3.3+1
  path_provider: ^2.1.4
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5
  image_picker: ^1.1.2
  intl: ^0.19.0
  input_quantity: ^2.4.0
  esc_pos_printer_plus: ^0.0.3
  image: ^4.2.0
  screenshot: ^3.0.0
  esc_pos_utils_plus: ^2.0.3
  mime: ^1.0.5
  http_parser: ^4.0.2
  fl_chart: ^0.69.0
  dropdown_button2: ^2.3.9

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner:
flutter:
  uses-material-design: true
  assets:
    - assets/lang/
